

INSERT INTO BOOK (TITLE) VALUES ('Lose the Fat Spell');
SET @book1 = LAST_INSERT_ID();
INSERT INTO BOOK (TITLE) VALUES ('Considerations of Magic');
SET @book2 = LAST_INSERT_ID();
INSERT INTO BOOK (TITLE) VALUES ('Life of A Magician');
SET @book3 = LAST_INSERT_ID();
INSERT INTO BOOK (TITLE) VALUES ('Magic in Practice');
SET @book4 = LAST_INSERT_ID();
INSERT INTO CUSTOMER (FIRSTNAME, LASTNAME, CUSTOMERTYPE) VALUES ('Jan', 'Krauser', 'SILVER');
SET @customer1 = LAST_INSERT_ID();
INSERT INTO CUSTOMER (FIRSTNAME, LASTNAME, CUSTOMERTYPE) VALUES ('Winnie', 'TheWoo', 'GOLD');
SET @customer2 = LAST_INSERT_ID();
INSERT INTO ADDRESS (STREET, CITY, CUSTOMER_ID) VALUES ('Hovedgaden 1', 'Byen', 1);
SET @address1 = LAST_INSERT_ID();
INSERT INTO ADDRESS (STREET, CITY, CUSTOMER_ID) VALUES ('Sidegaden 2', 'Landsbyen', 1);
SET @address2 = LAST_INSERT_ID();